// Auto-generated by scripts/build-okf.mjs from knowledge/projects/*.md
export const OKF_PROJECTS = [
  {
    "id": "beamfiber-portal",
    "type": "project",
    "title": "BeamFiber High-Speed ISP Customer Portal",
    "role": "Full-Stack Web Developer",
    "company": "Independent / Telecom",
    "date": "2023 - 2024",
    "stack": [
      "JavaScript",
      "HTML5",
      "CSS3",
      "Node.js",
      "REST APIs"
    ],
    "tags": [
      "Telecom",
      "Broadband Portal",
      "Customer Self-Service",
      "Responsive Web"
    ],
    "featured_on_website": false,
    "url": "https://github.com/sdhbyf2/beamfiber",
    "source": "Extended Project Dossier (Independent / Telecom)",
    "facts": "BeamFiber High-Speed ISP Customer Portal (Independent / Telecom, 2023 - 2024). Role: Full-Stack Web Developer. Stack: JavaScript, HTML5, CSS3, Node.js, REST APIs. A customer-facing telecom and internet service provider (ISP) portal enabling subscribers to explore fiber-optic internet plans, test bandwidth speeds, manage account subscriptions, and submit support tickets. Challenge: ISP customers require clear, real-time comparisons between bandwidth tiers (download/upload speeds, data limits, pricing) and instant self-service account management without calling customer support. Implementation: - **Plan Comparison Engine**: Built an interactive broadband plan selector with dynamic pricing calculators and speed tier filtering. - **Responsive Telecom UI**: Structured responsive layouts optimized for fast loading on mobile and desktop devices. - **RESTful API Services**: Connected backend service endpoints for billing inquiries, coverage checks, and customer service requests. Outcomes: - Simplified broadband plan selection and customer onboarding. - Open-source repository hosted on GitHub: https://github.com/sdhbyf2/beamfiber",
    "sections": {
      "content": "",
      "overview": "A customer-facing telecom and internet service provider (ISP) portal enabling subscribers to explore fiber-optic internet plans, test bandwidth speeds, manage account subscriptions, and submit support tickets.",
      "problem_challenge": "ISP customers require clear, real-time comparisons between bandwidth tiers (download/upload speeds, data limits, pricing) and instant self-service account management without calling customer support.",
      "technical_architecture_implementation": "- **Plan Comparison Engine**: Built an interactive broadband plan selector with dynamic pricing calculators and speed tier filtering. - **Responsive Telecom UI**: Structured responsive layouts optimized for fast loading on mobile and desktop devices. - **RESTful API Services**: Connected backend service endpoints for billing inquiries, coverage checks, and customer service requests.",
      "engineering_outcomes": "- Simplified broadband plan selection and customer onboarding. - Open-source repository hosted on GitHub: https://github.com/sdhbyf2/beamfiber"
    }
  },
  {
    "id": "betfred-migration",
    "type": "project",
    "title": "Betfred Platform Modernization & Latency Optimization",
    "role": "Senior Frontend Developer",
    "company": "Sharp Gaming",
    "date": "OCT 2022 — JUN 2023",
    "stack": [
      "React",
      "TypeScript",
      "Redux",
      "WebSockets",
      "Performance Profiling",
      "SonarQube"
    ],
    "tags": [
      "Fintech & Gaming",
      "High-Traffic Systems",
      "Architecture Modernization",
      "Team Mentoring"
    ],
    "featured_on_website": false,
    "url": "/#experience",
    "source": "Extended Project Dossier (Sharp Gaming)",
    "facts": "Betfred Platform Modernization & Latency Optimization (Sharp Gaming, OCT 2022 — JUN 2023). Role: Senior Frontend Developer. Stack: React, TypeScript, Redux, WebSockets, Performance Profiling, SonarQube. Led the enterprise frontend modernization and latency reduction initiative for Betfred, migrating core betting and gaming features from legacy vanilla JavaScript to a resilient React and TypeScript ecosystem. Challenge: High-concurrency live gaming and sports betting demand strict real-time updates and sub-100ms UI interaction latencies. The legacy JavaScript codebase suffered from regression risks, tight coupling, and difficult third-party game integration. Implementation: - **Architecture Migration**: Led the migration from legacy monolithic JavaScript into modular React 18, TypeScript, and Redux Toolkit architectures. - **Third-Party Game Engine Integration**: Built standardized integration layers and iframe messaging protocols for third-party gaming vendor content. - **Latency & Render Optimization**: Profiled memoization, Redux selectors, and WebSocket event batching to eliminate unnecessary re-renders during high-volume live odds changes. - **Engineering Quality Gates**: Enforced strict TypeScript linting rules, automated testing pipelines, and mentored junior and mid-level developers through thorough code reviews. Outcomes: - Substantial reduction in frontend regression bugs and developer onboarding time. - Smoother real-time odds rendering without UI freezes during peak sporting events. - Documented in Sudheer's career experience at Sharp Gaming (Manchester, UK).",
    "sections": {
      "content": "",
      "overview": "Led the enterprise frontend modernization and latency reduction initiative for Betfred, migrating core betting and gaming features from legacy vanilla JavaScript to a resilient React and TypeScript ecosystem.",
      "problem_challenge": "High-concurrency live gaming and sports betting demand strict real-time updates and sub-100ms UI interaction latencies. The legacy JavaScript codebase suffered from regression risks, tight coupling, and difficult third-party game integration.",
      "technical_architecture_implementation": "- **Architecture Migration**: Led the migration from legacy monolithic JavaScript into modular React 18, TypeScript, and Redux Toolkit architectures. - **Third-Party Game Engine Integration**: Built standardized integration layers and iframe messaging protocols for third-party gaming vendor content. - **Latency & Render Optimization**: Profiled memoization, Redux selectors, and WebSocket event batching to eliminate unnecessary re-renders during high-volume live odds changes. - **Engineering Quality Gates**: Enforced strict TypeScript linting rules, automated testing pipelines, and mentored junior and mid-level developers through thorough code reviews.",
      "engineering_outcomes": "- Substantial reduction in frontend regression bugs and developer onboarding time. - Smoother real-time odds rendering without UI freezes during peak sporting events. - Documented in Sudheer's career experience at Sharp Gaming (Manchester, UK)."
    }
  },
  {
    "id": "ecommerce-multistore",
    "type": "project",
    "title": "Concurrent Multi-Store E-Commerce Delivery",
    "role": "Senior Developer & Technical Lead",
    "company": "Crazy Techsol",
    "date": "MAY 2017 — JAN 2020",
    "stack": [
      "React",
      "TypeScript",
      "Redux",
      "Node.js",
      "PHP",
      "MySQL",
      "REST APIs",
      "Docker",
      "CI/CD"
    ],
    "tags": [
      "E-Commerce",
      "Multi-Store",
      "Component Systems",
      "Payment Gateways",
      "Team Leadership"
    ],
    "featured_on_website": false,
    "url": "/#experience",
    "source": "Extended Project Dossier (Crazy Techsol)",
    "facts": "Concurrent Multi-Store E-Commerce Delivery (Crazy Techsol, MAY 2017 — JAN 2020). Role: Senior Developer & Technical Lead. Stack: React, TypeScript, Redux, Node.js, PHP, MySQL, REST APIs, Docker, CI/CD. Directed and engineered concurrent full-stack e-commerce platforms and retail web systems for 8+ concurrent commercial stores, scaling checkout throughput and modernizing legacy stacks. Challenge: Multiple client stores were running disparate, legacy PHP and jQuery architectures with inconsistent cart state management, sluggish checkout funnels, and manual deployment vulnerabilities. Implementation: - **Full-Stack Re-architecture**: Migrated legacy PHP/jQuery interfaces into unified React, TypeScript, and Redux single-page applications connected to Node.js / PHP backend APIs. - **Shared Component Library**: Designed and distributed an internal UI component system across stores, ensuring consistent branding, responsive design, and rapid feature rollouts. - **Payment & Inventory Integrations**: Integrated robust payment gateways, automated invoice workflows, and real-time inventory synchronization. - **CI/CD & Documentation**: Established automated Git workflows, CI/CD deployment pipelines, and comprehensive technical architecture documentation. Outcomes: - Successfully delivered and maintained 8+ active online stores simultaneously. - Drastically reduced checkout abandonment rates through seamless, modern single-page checkout flows. - Led and mentored a team of developers while managing client technical delivery and architecture.",
    "sections": {
      "content": "",
      "overview": "Directed and engineered concurrent full-stack e-commerce platforms and retail web systems for 8+ concurrent commercial stores, scaling checkout throughput and modernizing legacy stacks.",
      "problem_challenge": "Multiple client stores were running disparate, legacy PHP and jQuery architectures with inconsistent cart state management, sluggish checkout funnels, and manual deployment vulnerabilities.",
      "technical_architecture_implementation": "- **Full-Stack Re-architecture**: Migrated legacy PHP/jQuery interfaces into unified React, TypeScript, and Redux single-page applications connected to Node.js / PHP backend APIs. - **Shared Component Library**: Designed and distributed an internal UI component system across stores, ensuring consistent branding, responsive design, and rapid feature rollouts. - **Payment & Inventory Integrations**: Integrated robust payment gateways, automated invoice workflows, and real-time inventory synchronization. - **CI/CD & Documentation**: Established automated Git workflows, CI/CD deployment pipelines, and comprehensive technical architecture documentation.",
      "engineering_outcomes": "- Successfully delivered and maintained 8+ active online stores simultaneously. - Drastically reduced checkout abandonment rates through seamless, modern single-page checkout flows. - Led and mentored a team of developers while managing client technical delivery and architecture."
    }
  },
  {
    "id": "foot-doctor",
    "type": "project",
    "title": "Foot Doctor Podiatry Platform",
    "role": "Full-Stack Engineer",
    "company": "Independent Healthcare Project",
    "date": "2024 - 2025",
    "stack": [
      "TypeScript",
      "React",
      "Next.js",
      "Node.js",
      "Tailwind CSS",
      "REST APIs"
    ],
    "tags": [
      "Healthcare",
      "Patient Scheduling",
      "Responsive UI",
      "Digital Health"
    ],
    "featured_on_website": false,
    "url": "https://github.com/sdhbyf2/foot-doctor",
    "source": "Extended Project Dossier (Independent Healthcare Project)",
    "facts": "Foot Doctor Podiatry Platform (Independent Healthcare Project, 2024 - 2025). Role: Full-Stack Engineer. Stack: TypeScript, React, Next.js, Node.js, Tailwind CSS, REST APIs. A modern digital health and clinic web platform designed for podiatry and foot specialist practices, streamlining patient discovery, clinical treatment explanations, and appointment inquiries. Challenge: Specialist healthcare clinics often struggle with fragmented patient communication, unintuitive treatment service navigation, and slow mobile load times on outdated CMS setups. Implementation: - **Frontend Architecture**: Built with modern React and TypeScript on Next.js, ensuring strong type safety and server-rendered performance. - **Component Design System**: Structured reusable clinic components with Tailwind CSS for accessible, high-contrast healthcare presentation adhering to WCAG standards. - **Service & Inquiries Routing**: Integrated RESTful API routes for patient booking inquiries and clinic schedule notifications. Outcomes: - Clean, responsive mobile-first experience with sub-second page loads. - Fully typed component codebase with zero runtime prop errors. - Open-source repository available on GitHub: https://github.com/sdhbyf2/foot-doctor",
    "sections": {
      "content": "",
      "overview": "A modern digital health and clinic web platform designed for podiatry and foot specialist practices, streamlining patient discovery, clinical treatment explanations, and appointment inquiries.",
      "problem_challenge": "Specialist healthcare clinics often struggle with fragmented patient communication, unintuitive treatment service navigation, and slow mobile load times on outdated CMS setups.",
      "technical_architecture_implementation": "- **Frontend Architecture**: Built with modern React and TypeScript on Next.js, ensuring strong type safety and server-rendered performance. - **Component Design System**: Structured reusable clinic components with Tailwind CSS for accessible, high-contrast healthcare presentation adhering to WCAG standards. - **Service & Inquiries Routing**: Integrated RESTful API routes for patient booking inquiries and clinic schedule notifications.",
      "engineering_outcomes": "- Clean, responsive mobile-first experience with sub-second page loads. - Fully typed component codebase with zero runtime prop errors. - Open-source repository available on GitHub: https://github.com/sdhbyf2/foot-doctor"
    }
  }
];

export function searchOkfProjects(query = "") {
  if (!query || typeof query !== "string") return [];
  const q = query.toLowerCase().trim();
  const words = q.split(/\s+/).filter(Boolean);
  return OKF_PROJECTS.filter((p) => {
    const searchable = `${p.id} ${p.title} ${p.role} ${p.company} ${p.stack.join(" ")} ${p.tags.join(" ")} ${p.facts}`.toLowerCase();
    return (
      searchable.includes(q) ||
      searchable.includes(q.replace(/\s+/g, "")) ||
      (words.length > 1 && words.every((w) => searchable.includes(w)))
    );
  });
}
