import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const projectsDir = path.join(rootDir, 'knowledge', 'projects');
const outputJsPath = path.join(rootDir, 'knowledge', 'registry.js');
const outputJsonPath = path.join(rootDir, 'knowledge', 'index.json');

function parseYamlValue(raw) {
  raw = raw.trim();
  if (raw.startsWith('[') && raw.endsWith(']')) {
    return raw
      .slice(1, -1)
      .split(',')
      .map(s => s.trim().replace(/^['"]|['"]$/g, ''))
      .filter(Boolean);
  }
  if (raw === 'true') return true;
  if (raw === 'false') return false;
  return raw.replace(/^['"]|['"]$/g, '');
}

function parseMarkdownOkf(rawContent) {
  const match = rawContent.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) return null;

  const frontmatterRaw = match[1];
  const body = match[2].trim();
  const meta = {};

  for (const line of frontmatterRaw.split('\n')) {
    const colonIndex = line.indexOf(':');
    if (colonIndex > 0) {
      const key = line.slice(0, colonIndex).trim();
      const val = line.slice(colonIndex + 1).trim();
      meta[key] = parseYamlValue(val);
    }
  }

  // Extract sections from markdown body
  const sections = {};
  let currentHeader = 'content';
  sections[currentHeader] = [];

  for (const line of body.split('\n')) {
    const headingMatch = line.match(/^##\s+(.+)$/);
    if (headingMatch) {
      currentHeader = headingMatch[1].trim().toLowerCase().replace(/[^a-z0-9]+/g, '_');
      sections[currentHeader] = [];
    } else {
      sections[currentHeader].push(line);
    }
  }

  for (const [k, lines] of Object.entries(sections)) {
    sections[k] = lines.join(' ').replace(/\s+/g, ' ').trim();
  }

  const overview = sections['overview'] || sections['summary'] || '';
  const challenge = sections['problem_challenge'] || sections['challenge'] || '';
  const architecture = sections['technical_architecture_implementation'] || sections['architecture'] || '';
  const outcomes = sections['engineering_outcomes'] || sections['outcomes'] || '';

  const facts = `${meta.title} (${meta.company || 'Project'}, ${meta.date || ''}). Role: ${meta.role || 'Engineer'}. Stack: ${(meta.stack || []).join(', ')}. ${overview} ${challenge ? 'Challenge: ' + challenge : ''} ${architecture ? 'Implementation: ' + architecture : ''} ${outcomes ? 'Outcomes: ' + outcomes : ''}`.replace(/\s+/g, ' ').trim();

  return {
    id: meta.id,
    type: meta.type || 'project',
    title: meta.title,
    role: meta.role || '',
    company: meta.company || '',
    date: meta.date || '',
    stack: Array.isArray(meta.stack) ? meta.stack : [],
    tags: Array.isArray(meta.tags) ? meta.tags : [],
    featured_on_website: Boolean(meta.featured_on_website),
    url: meta.url || '/#experience',
    source: `Extended Project Dossier (${meta.company || 'Independent'})`,
    facts,
    sections,
  };
}

export function buildOkf() {
  if (!fs.existsSync(projectsDir)) {
    fs.mkdirSync(projectsDir, { recursive: true });
  }

  const files = fs.readdirSync(projectsDir).filter(f => f.endsWith('.md'));
  const projects = [];

  for (const file of files) {
    const fullPath = path.join(projectsDir, file);
    const content = fs.readFileSync(fullPath, 'utf8');
    const parsed = parseMarkdownOkf(content);
    if (parsed && parsed.id) {
      projects.push(parsed);
    }
  }

  fs.writeFileSync(outputJsonPath, JSON.stringify(projects, null, 2), 'utf8');

  const jsContent = `// Auto-generated by scripts/build-okf.mjs from knowledge/projects/*.md
export const OKF_PROJECTS = ${JSON.stringify(projects, null, 2)};

export function searchOkfProjects(query = "") {
  if (!query || typeof query !== "string") return [];
  const q = query.toLowerCase().trim();
  const words = q.split(/\\s+/).filter(Boolean);
  return OKF_PROJECTS.filter((p) => {
    const searchable = \`\${p.id} \${p.title} \${p.role} \${p.company} \${p.stack.join(" ")} \${p.tags.join(" ")} \${p.facts}\`.toLowerCase();
    return (
      searchable.includes(q) ||
      searchable.includes(q.replace(/\\s+/g, "")) ||
      (words.length > 1 && words.every((w) => searchable.includes(w)))
    );
  });
}
`;

  fs.writeFileSync(outputJsPath, jsContent, 'utf8');
  console.log(`Successfully compiled ${projects.length} OKF project documents into knowledge/registry.js and knowledge/index.json`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  buildOkf();
}
